### ISSUE TITLE
Question on the integration

### ISSUE THREAD

**Issue by TatisLois** [nikolaxhristov/astro-short-urls#59]
So does this integration turn a url like

```
www.example.com/some-long-page <-- my site
```
into
```
www.example.com/slp <--- shorten
```

and maintain the mapping?

**Comment by nikolaxhristov** [comment]
It still doesn't work it's just a placeholder but it will wrap `lychee` https://github.com/lycheeverse/lychee into a dashboard for you to use I just haven't got the time to develop it yet.

**Comment by nikolaxhristov** [comment]
> So does this integration turn a url like
> 
> ```
> www.example.com/some-long-page <-- my site
> ```
> 
> into
> 
> ```
> www.example.com/slp <--- shorten
> ```
> 
> and maintain the mapping?

But that's the general gist.
